### PR TITLE
* Update: Adding default configuration file for setting system variables and snmp version

### PR DESCRIPTION
**Pull request by Tejaswi-Goel**
Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

Test to ensure everything works:
1) snmpwalk -v2c -c public localhost 1.3.6.1.2.1.1
iso.3.6.1.2.1.1.1.0 = STRING: "Platform:S6010-ON, NOS:OPX2.3.1"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.674
iso.3.6.1.2.1.1.3.0 = Timeticks: (10769) 0:01:47.69
iso.3.6.1.2.1.1.4.0 = STRING: "OpenSwitch.net"
iso.3.6.1.2.1.1.5.0 = STRING: "OPX"
iso.3.6.1.2.1.1.6.0 = STRING: "Santa Clara, CA"
iso.3.6.1.2.1.1.7.0 = INTEGER: 6
iso.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00

### CODE REVIEW

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 6306c908b3a2102f0ca4e3f96063a553b8a3c460

**Review by nchervela — DISMISSED** [review]
Already reviewed on gerritt

**Review by jeffyin-dell — CHANGES_REQUESTED** [review]
Please address the 2 issues reported by the CodeFactor check (extraneous newline and unused var) 
https://www.codefactor.io/repository/github/open-switch/opx-snmp/pull/1

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now de42025d4cd46bd8c584c67d102b642248a616e4

**Review by jeffyin-dell — APPROVED** [review]

**Pull request merged**
