### PR TITLE
fix: Display linux name of interfaces

### PR DESCRIPTION
**Pull request by nchervela**
Signed-off-by: Nalini Chervela <nalini_chervela@dell.com>

### CODE REVIEW

**Review by atanu-mandal — CHANGES_REQUESTED** [review]
Please update the changelog and bump up the version
(in changelog and configure.ac)

**Comment by Tejaswi-Goel** [comment]
Please update the debian/changelog and configure.ac.

**Comment by nchervela** [comment]
Pull-request updated, HEAD is now 0d613c7983a059ec45770af6fe093938121ed03f

**Review by Tejaswi-Goel — APPROVED** [review]

**Comment by nchervela** [comment]
@atanu-mandal  updated changelog and configure.ac, thanks.

**Pull request merged**
